# URL generated by CloudFront
output "website_url" {
  description = "The public URL of the CloudFront distribution"
  value       = aws_cloudfront_distribution.s3_distribution.domain_name
}

# The unique name of the S3 bucket
output "bucket_name" {
  description = "The name of the S3 bucket hosting the resume"
  value       = aws_s3_bucket.website_bucket.id
}

# The CloudFront Distribution ID (Useful for later when we automate deployments)
output "cloudfront_distribution_id" {
  description = "The ID of the CloudFront distribution"
  value       = aws_cloudfront_distribution.s3_distribution.id
}

# The name of the DynamoDB Table
output "dynamodb_table_name" {
  description = "The name of the DynamoDB table"
  value       = aws_dynamodb_table.visitor_count.name
}

# The Invoke URL for the API Gateway
output "api_url" {
  description = "The Invoke URL for the API Gateway"
  value       = aws_apigatewayv2_api.http_api.api_endpoint
}

output "state_bucket_name" {
  value = aws_s3_bucket.terraform_state.id
}